import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';
import 'package:mockito/annotations.dart';
import 'package:your_project_name/features/activity/application/activity_notifier.dart'; // Replace your_project_name
import 'package:your_project_name/features/activity/application/activity_state.dart'; // Replace your_project_name
import 'package:your_project_name/features/activity/domain/contracts/i_activity_service.dart'; // Replace your_project_name
import 'package:your_project_name/core/domain/data_state.dart'; // Replace your_project_name
import 'package:your_project_name/features/activity/domain/activity.dart'; // Replace your_project_name
import 'package:your_project_name/features/activity/domain/activity_log.dart'; // Replace your_project_name
import 'package:your_project_name/core/domain/result.dart'; // Replace your_project_name
import 'dart:async';

import 'activity_notifier_test.mocks.dart'; // Generated by build_runner

// Annotations for generating mocks
@GenerateMocks([IActivityService])
void main() {
  late MockIActivityService mockActivityService;
  late ActivityNotifier activityNotifier;
  late List<ActivityState> states;
  late DateTime testDate;

  final mockActivity = Activity(id: 'act1', name: 'Walking', metValue: 3.0);
  final mockActivityLog = ActivityLog(
    id: 'log1',
    activity: mockActivity,
    duration: Duration(minutes: 30),
    caloriesBurned: 120,
    loggedAt: DateTime.now(),
  );

  setUp(() {
    mockActivityService = MockIActivityService();
    activityNotifier = ActivityNotifier(mockActivityService);
    states = [];
    activityNotifier.addListener((state) {
      states.add(state);
    });
    testDate = DateTime(2023, 10, 26);

    // Default stubs for methods called during initialization or common operations
    when(mockActivityService.getCommonActivities()).thenAnswer((_) async => Result.success([mockActivity]));
    when(mockActivityService.getActivityLogsForDate(any)).thenAnswer((_) async => Result.success([mockActivityLog]));
    when(mockActivityService.getCaloriesBurnedForDate(any)).thenAnswer((_) async => Result.success(120.0));
    when(mockActivityService.getTotalCaloriesBurnedWithBmrForDate(any, any)).thenAnswer((_) async => Result.success(1500.0));
  });

  tearDown(() {
    activityNotifier.dispose();
  });

  group('ActivityNotifier', () {
    group('Initial State', () {
      test('should initialize with ActivityState.initial()', () {
        expect(activityNotifier.debugState, equals(ActivityState.initial()));
        expect(states.isEmpty, isTrue); // Listener should not be called yet
      });
    });

    group('initialize()', () {
      test('should call service methods and update state through loading to success', () async {
        // Arrange
        when(mockActivityService.getCommonActivities()).thenAnswer((_) async => Result.success([mockActivity]));
        when(mockActivityService.getActivityLogsForDate(any)).thenAnswer((_) async => Result.success([mockActivityLog]));
        when(mockActivityService.getCaloriesBurnedForDate(any)).thenAnswer((_) async => Result.success(150.0));

        // Act
        await activityNotifier.initialize();

        // Assert
        verify(mockActivityService.getCommonActivities()).called(1);
        verify(mockActivityService.getActivityLogsForDate(activityNotifier.debugState.selectedDate)).called(1);
        verify(mockActivityService.getCaloriesBurnedForDate(activityNotifier.debugState.selectedDate)).called(1);

        expect(states.length, greaterThanOrEqualTo(3)); // At least common, activities, calories

        // Check intermediate loading states (example for common activities)
        expect(states.where((s) => s.commonActivitiesState == DataState.loading()).isNotEmpty, isTrue);
        expect(states.last.commonActivitiesState, DataState.success([mockActivity]));
        expect(states.last.todaysActivitiesState, DataState.success([mockActivityLog]));
        expect(states.last.todaysCaloriesState, DataState.success(150.0));
      });

      test('should handle errors from service methods', () async {
        // Arrange
        when(mockActivityService.getCommonActivities()).thenAnswer((_) async => Result.failure('Failed to load common'));
        when(mockActivityService.getActivityLogsForDate(any)).thenAnswer((_) async => Result.failure('Failed to load activities'));
        when(mockActivityService.getCaloriesBurnedForDate(any)).thenAnswer((_) async => Result.failure('Failed to load calories'));

        // Act
        await activityNotifier.initialize();

        // Assert
        expect(states.last.commonActivitiesState, DataState.error('Failed to load common'));
        expect(states.last.todaysActivitiesState, DataState.error('Failed to load activities'));
        expect(states.last.todaysCaloriesState, DataState.error('Failed to load calories'));
      });
    });

    group('initializeWithBmr()', () {
      const bmr = 1500.0;
      test('should call service methods and update state', () async {
        // Arrange
        when(mockActivityService.getActivityLogsForDate(any)).thenAnswer((_) async => Result.success([mockActivityLog]));
        when(mockActivityService.getTotalCaloriesBurnedWithBmrForDate(any, bmr)).thenAnswer((_) async => Result.success(1650.0));

        // Act
        await activityNotifier.initializeWithBmr(bmr);

        // Assert
        verify(mockActivityService.getActivityLogsForDate(activityNotifier.debugState.selectedDate)).called(1);
        verify(mockActivityService.getTotalCaloriesBurnedWithBmrForDate(activityNotifier.debugState.selectedDate, bmr)).called(1);

        expect(states.last.todaysActivitiesState, DataState.success([mockActivityLog]));
        expect(states.last.todaysCaloriesState, DataState.success(1650.0));
        expect(activityNotifier.debugState.currentBmr, bmr);
      });
    });

    group('setSelectedDate()', () {
      final newDate = DateTime(2023, 11, 15);
      test('should update selectedDate and reload data', () async {
        // Arrange
        when(mockActivityService.getActivityLogsForDate(newDate)).thenAnswer((_) async => Result.success([mockActivityLog]));
        when(mockActivityService.getCaloriesBurnedForDate(newDate)).thenAnswer((_) async => Result.success(100.0));

        // Act
        await activityNotifier.setSelectedDate(newDate);

        // Assert
        expect(activityNotifier.debugState.selectedDate, newDate);
        verify(mockActivityService.getActivityLogsForDate(newDate)).called(1);
        verify(mockActivityService.getCaloriesBurnedForDate(newDate)).called(1);
        expect(states.last.todaysActivitiesState, DataState.success([mockActivityLog]));
        expect(states.last.todaysCaloriesState, DataState.success(100.0));
      });

      test('should reload data with BMR if currentBmr is set', () async {
        // Arrange
        const bmr = 1600.0;
        await activityNotifier.initializeWithBmr(bmr); // Set BMR
        states.clear(); // Clear initial states

        when(mockActivityService.getActivityLogsForDate(newDate)).thenAnswer((_) async => Result.success([mockActivityLog]));
        when(mockActivityService.getTotalCaloriesBurnedWithBmrForDate(newDate, bmr)).thenAnswer((_) async => Result.success(1700.0));

        // Act
        await activityNotifier.setSelectedDate(newDate);

        // Assert
        expect(activityNotifier.debugState.selectedDate, newDate);
        verify(mockActivityService.getActivityLogsForDate(newDate)).called(1);
        verify(mockActivityService.getTotalCaloriesBurnedWithBmrForDate(newDate, bmr)).called(1);
        verifyNever(mockActivityService.getCaloriesBurnedForDate(newDate));
        expect(states.last.todaysCaloriesState, DataState.success(1700.0));
      });
    });

    group('loadCommonActivities()', () {
      test('should update commonActivitiesState on success', () async {
        when(mockActivityService.getCommonActivities()).thenAnswer((_) async => Result.success([mockActivity]));
        await activityNotifier.loadCommonActivities();
        expect(states.first.commonActivitiesState, DataState.loading());
        expect(states.last.commonActivitiesState, DataState.success([mockActivity]));
      });
      test('should update commonActivitiesState on failure', () async {
        when(mockActivityService.getCommonActivities()).thenAnswer((_) async => Result.failure('Error'));
        await activityNotifier.loadCommonActivities();
        expect(states.first.commonActivitiesState, DataState.loading());
        expect(states.last.commonActivitiesState, DataState.error('Error'));
      });
    });

    group('searchActivities()', () {
      test('should set searchResultsState to idle if query is empty', () async {
        await activityNotifier.searchActivities('');
        expect(activityNotifier.debugState.searchQuery, isEmpty);
        expect(activityNotifier.debugState.searchResultsState, DataState.idle());
        expect(states.last.searchResultsState, DataState.idle());
      });

      test('should update searchResultsState on success', () async {
        when(mockActivityService.searchActivities('run')).thenAnswer((_) async => Result.success([mockActivity]));
        await activityNotifier.searchActivities('run');
        expect(activityNotifier.debugState.searchQuery, 'run');
        expect(states.first.searchResultsState, DataState.loading());
        expect(states.last.searchResultsState, DataState.success([mockActivity]));
      });

      test('should update searchResultsState on failure', () async {
        when(mockActivityService.searchActivities('run')).thenAnswer((_) async => Result.failure('Search Error'));
        await activityNotifier.searchActivities('run');
        expect(states.first.searchResultsState, DataState.loading());
        expect(states.last.searchResultsState, DataState.error('Search Error'));
      });
    });

    // ... More tests for other methods:
    // loadActivitiesForDate, loadCaloriesBurnedForDate, loadTotalCaloriesWithBmrForDate
    // logActivity, calculateCalories, deleteActivity, updateActivity
    // clearSearch, refresh, dispose

    group('logActivity()', () {
      final params = LogActivityParams(activityId: 'act1', durationInMinutes: 30, loggedAt: testDate, specificMET: null);
      test('should set isLoggingActivity and reload data on success', () async {
        when(mockActivityService.logActivity(params)).thenAnswer((_) async => Result.success(mockActivityLog));
        // Assuming no BMR is set for simplicity, will call getCaloriesBurnedForDate
        when(mockActivityService.getCaloriesBurnedForDate(testDate)).thenAnswer((_) async => Result.success(200.0));


        bool callbackCalled = false;
        activityNotifier.onActivityChanged = () => callbackCalled = true;

        await activityNotifier.setSelectedDate(testDate); // Ensure selectedDate is set
        states.clear();

        final result = await activityNotifier.logActivity(params: params);

        expect(result, isTrue);
        expect(states.first.isLoggingActivity, isTrue);
        expect(states.last.isLoggingActivity, isFalse);

        verify(mockActivityService.logActivity(params)).called(1);
        verify(mockActivityService.getActivityLogsForDate(testDate)).called(1); // Reloads activities
        verify(mockActivityService.getCaloriesBurnedForDate(testDate)).called(1); // Reloads calories
        expect(callbackCalled, isTrue);
      });

       test('should reload calories with BMR if BMR is set on success', () async {
        const bmr = 1500.0;
        await activityNotifier.initializeWithBmr(bmr);
        await activityNotifier.setSelectedDate(testDate);
        states.clear();

        when(mockActivityService.logActivity(params)).thenAnswer((_) async => Result.success(mockActivityLog));
        when(mockActivityService.getTotalCaloriesBurnedWithBmrForDate(testDate, bmr)).thenAnswer((_) async => Result.success(1700.0));


        final result = await activityNotifier.logActivity(params: params);

        expect(result, isTrue);
        verify(mockActivityService.getTotalCaloriesBurnedWithBmrForDate(testDate, bmr)).called(1);
        verifyNever(mockActivityService.getCaloriesBurnedForDate(testDate));
      });

      test('should handle failure from service', () async {
        when(mockActivityService.logActivity(params)).thenAnswer((_) async => Result.failure('Log Error'));

        final result = await activityNotifier.logActivity(params: params);

        expect(result, isFalse);
        expect(states.first.isLoggingActivity, isTrue);
        expect(states.last.isLoggingActivity, isFalse);
        verifyNever(mockActivityService.getActivityLogsForDate(any));
        verifyNever(mockActivityService.getCaloriesBurnedForDate(any));
      });
    });

    group('clearSearch()', () {
      test('should clear searchQuery and set searchResultsState to idle', () async {
        // First, perform a search to populate the state
        when(mockActivityService.searchActivities('test')).thenAnswer((_) async => Result.success([mockActivity]));
        await activityNotifier.searchActivities('test');
        expect(activityNotifier.debugState.searchQuery, 'test');
        expect(activityNotifier.debugState.searchResultsState, DataState.success([mockActivity]));
        states.clear();

        // Now, clear the search
        activityNotifier.clearSearch();

        expect(activityNotifier.debugState.searchQuery, isEmpty);
        expect(activityNotifier.debugState.searchResultsState, DataState.idle());
        expect(states.last.searchQuery, isEmpty);
        expect(states.last.searchResultsState, DataState.idle());
      });
    });

    group('dispose()', () {
      test('should set _isDisposed to true and not update state after disposal', () async {
        expect(activityNotifier.debugIsDisposed, isFalse);
        activityNotifier.dispose();
        expect(activityNotifier.debugIsDisposed, isTrue);

        states.clear();
        // Try to trigger a state change
        await activityNotifier.loadCommonActivities();
        expect(states.isEmpty, isTrue); // No new states should be added
      });
    });

    // Note: Testing static refreshAllInstances() is complex in unit tests.
    // It might be better tested via integration tests or by observing its effects
    // if other notifiers are involved.
  });
}
